# automatically deposit data to EDI

# raw NEON data

# L1 data generated by ecocomDP

# L2 data frames that will be available in this data package

if(!require(neonDivData)) devtools::install_github("daijiang/neonDivData")
library(neonDivData)
library(dplyr)

# filter provisional data out
table(data_algae$release)

if(!dir.exists("data-raw/edi")) dir.create("data-raw/edi")
# save all flatterned data frames to csv
write.csv(filter(data_algae, release != "PROVISIONAL"), file = "data-raw/edi/data_algae.csv", row.names = FALSE)
write.csv(filter(data_beetle, release != "PROVISIONAL"), file = "data-raw/edi/data_beetle.csv", row.names = FALSE)
write.csv(filter(data_bird, release != "PROVISIONAL"), file = "data-raw/edi/data_bird.csv", row.names = FALSE)
write.csv(filter(data_fish, release != "PROVISIONAL"), file = "data-raw/edi/data_fish.csv", row.names = FALSE)
write.csv(filter(data_herp_bycatch, release != "PROVISIONAL"), file = "data-raw/edi/data_herp_bycatch.csv", row.names = FALSE)
write.csv(filter(data_macroinvertebrate, release != "PROVISIONAL"), file = "data-raw/edi/data_macroinvertebrate.csv", row.names = FALSE)
write.csv(filter(data_mosquito, release != "PROVISIONAL"), file = "data-raw/edi/data_mosquito.csv", row.names = FALSE)
write.csv(filter(data_plant, release != "PROVISIONAL"), file = "data-raw/edi/data_plant.csv", row.names = FALSE)
write.csv(filter(data_small_mammal, release != "PROVISIONAL"), file = "data-raw/edi/data_small_mammal.csv", row.names = FALSE)
write.csv(filter(data_tick, release != "PROVISIONAL"), file = "data-raw/edi/data_tick.csv", row.names = FALSE)
write.csv(filter(data_tick_pathogen, release != "PROVISIONAL"), file = "data-raw/edi/data_tick_pathogen.csv", row.names = FALSE)
write.csv(filter(data_zooplankton, release != "PROVISIONAL"), file = "data-raw/edi/data_zooplankton.csv", row.names = FALSE)

# location info are already in the above data objects,
# but I did extract all of them and put them in one file
write.csv(neon_location, file = "data-raw/edi/neon_location.csv", row.names = FALSE)

write.csv(neon_sites, file = "data-raw/edi/neon_sites.csv", row.names = FALSE)

# taxa code and scientific names
write.csv(neon_taxa, file = "data-raw/edi/neon_taxa.csv", row.names = FALSE)

# summary information
write.csv(data_summary, file = "data-raw/edi/data_summary.csv", row.names = FALSE)

# how to deposit csv files to EDI? Or just rds file?

# remove all RDS files
system("rm -r data-raw/neon_div_data data-raw/NEON_raw_data")
