# automatically deposit data to EDI

# raw NEON data

# L1 data generated by ecocomDP

# L2 data frames that will be available in this data package



# remove all RDS files
system("rm -r data-raw/neon_div_data data-raw/NEON_raw_data")
